version: "3.8"

services:
  spring-api:
    image: spring-app
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:8080"
    volumes:
      - /home/vicheak/docker/spring-api/workspace:/workspace
    networks:
      - api-network

networks:
  api-network: