version: '3.8' 

services:
  sonarqube:
    image: sonarqube:latest  
    container_name: sonarqube
    ports:
      - "5004:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=admincheak112233
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    depends_on:
      - sonarqube-db
    restart: always

  sonarqube-db:
    image: postgres:14
    container_name: sonarqube-postgres-db
    ports:
      - "5005:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admincheak112233
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    restart: always

volumes:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:
  postgres-data:
