version: '3'

services: 
  jenkins: 
    container_name: jenkins
    image: jenkins_install_jenkins:latest
    build:
      context: . 
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports: 
      - "5003:8080"
      - "50000:50000"
      # this port 50000 is for the agent communication (worker)
    volumes : 
      - jenkins_home:/var/jenkins_home
      # below are bind mount
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/trivy:/usr/bin/trivy
      - ./ansible:/ansible
  
volumes:
  jenkins_home: