version: '3.8'

services:
  gitdeploy:
    image: 'gitlab/gitlab-ee:latest'
    container_name: gitlab-app
    restart: always
    hostname: 'gitlab.begoingdev.me'
    environment:
      GITLAB_OMNIBUS_CONFIG: |    
        external_url 'https://gitlab.begoingdev.me'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '2100:80'
      - '2101:443'
      - '2225:22'
    volumes:
      - '/etc/gitlab/config:/etc/gitlab'
      - '/etc/gitlab/logs:/var/log/gitlab'
      - '/etc/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'